---
- name: lesson1.3
  hosts: nodes
  tasks:
  - name: string validation in GRUB file [net.ifnames=0 biosdevname=0]
    lineinfile:
      state: present
      path: '/etc/default/grub'
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=0 biosdevname=0)\"[^\"]+)(\".*)'
      line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"'
      backup: yes
  - name: shell command for grub
    shell:
      cmd: grub2-mkconfig
...
