---
# tasks file for deploy_apache_centos
- name: Install, configure and start Apache on nodes for CentOS
  block:
    - name: Install Apache for CentOS
      yum:
        name: httpd
        state: latest

    - name: Start Apache for CentOS
      systemd:
        name: httpd
        state: started

    - name: created file index.html for CentOS
      template:
        src: index.j2
        dest: '{{dest_index}}/index.html'
        owner: apache
        group: apache
        mode: 0644
      notify:
        - Restart Apache CentOS
  when: ansible_distribution == 'CentOS'

- name: Install, configure and start Apache on nodes for Debian
  block:
    - name: Install Apache for Debian
      apt:
        name: apache2
        state: latest

    - name: enabled Apache for Debian
      systemd:
        name: apache2
        state: started

    - name: created file index.html for Debian
      template:
        src: index.j2
        dest: '{{dest_index}}/index.html'
        owner: apache
        group: apache
        mode: 0644
      notify:
        - Restart Apache Debian
  when: ansible_distribution == 'Debian'
     
- name: Open ports for httpd
  firewalld:
    service: http
    permanent: yes
    state: enabled